[package]
name = "retl"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.15"
pest_derive  = "2.7.15"
memchr = "2.7.4"
regex = { version = "1.11.1", features = ["std", "unicode", "perf"] }
regex-syntax = {version = "0.8.5", features = ["unicode"]}
chrono = "0.4.39"