[package]
name = "retl"
version = "0.1.0"
edition = "2024"

[dependencies]
flexi_logger = "0.29"
log = "0.4"
dyn-clone = "1.0.18"
pest = "2.7.15"
pest_derive  = "2.7.15"
memchr = "2.7.4"
regex = { version = "1.11.1", features = ["std", "unicode", "perf"] }
regex-syntax = {version = "0.8.5", features = ["unicode"]}
indexmap = "2.7"
chrono = "0.4.39"
itertools = "0.14.0"
rand = "0.9.0"
rand_regex = "0.18.0"
#regex_generate = "0.2.3"
serde = "1.0.194"
serde-value = "0.7.0"
serde_json = "1.0.138"
serde_yaml = "0.9"
typetag = "0.2"
config = { version = "0.15.8", features = ["yaml"] }
# simd-json = "0.14.3"
rdkafka = { version = "0.37.0", features = ["cmake-build"] }

[build]
rustflags = ["-A", "warnings"]