[package]
name = "retl"
version = "0.1.0"
edition = "2021"

[dependencies]
flexi_logger = "0.29"
log = "0.4"
pest = "2.7.15"
pest_derive  = "2.7.15"
memchr = "2.7.4"
regex = { version = "1.11.1", features = ["std", "unicode", "perf"] }
regex-syntax = {version = "0.8.5", features = ["unicode"]}
chrono = "0.4.39"
itertools = "0.14.0"
rand = "0.9.0"
rand_regex = "0.18.0"
#regex_generate = "0.2.3"
serde = "1.0.194"
serde_json = "1.0.138"
serde_yaml = "0.9"
# simd-json = "0.14.3"
rdkafka = { version = "0.37.0", features = ["cmake-build"] }