env:
  application:
    name: test
    parallelism: 1

sources:
  - type: inline
    outputs: [ inline_source ]
    schema: |
      os_type int,
      os_plant string,
      page_id string,
      page_name string,
      page_param string,
      visit_time string
    data: |
      [
        {"os_type": 4, "os_plant": "IOS-M", "page_id": "Product_Main", "page_name": "pp.com/118065875", "page_param": "searchText=男表&lng=112.935037&lat=23.031227", "visit_time": "2025-05-01 08:12:45"}
      ]
    rows_per_second: 10
    number_of_rows: 1
    decoding:
      codec: json

transforms:
  - type: query
    inputs: [ inline_source ]
    outputs: [ query ]
    sql: |
      select 
          os_type,
          if(os_type=4, 'IOS', 'ANDROID'),
          if(os_type in (3, 4), 'IOS', 'ANDROID'),
          case os_type
            when 1 then 'ANDROID'
            when 2 then 'ANDROID-M'
            when 3 then 'IOS'
            when 4 then 'IOS-M'
            else 'OTHER'
          end,
          nvl(os_type, 0),
          coalesce(null, 1, 0),
          greatest(1, 2, 3, 1),
          least(1, 2, 3, 1),
          5 + 3,
          5 - 3,
          5 * 3,
          5 / 3,
          5 % 3,
          5 = 3,
          5 != 3,
          5 > 3,
          5 >= 3,
          5 < 3,
          5 <= 3,
          5 > 3 and 5 < 3,
          5 > 3 or 5 < 3,
          not 5 > 3,
          3 in (1,2,3),
          length(page_id),
          trim(page_id),
          lower(page_id),
          upper(page_id),
          substr(page_id, 1, 4),
          concat(os_plant, '|', page_id),
          concat_ws('|', os_plant, page_id),
          split(page_param, '&'),
          split_part(page_param, '&', 1),
          split_part(page_param, '&', 0),
          replace(page_param, '&', '#'),
          page_name,
          page_name like '%pp.com%',
          page_name rlike 'pp.com/[0-9]+',
          page_name regexp 'pp.com/[0-9]+' `page_name regexp 'pp.com/[0-9]+'`,
          regexp_extract(page_name, 'pp.com/([0-9]+)', 1),
          page_param,
          regexp_extract(page_param, 'searchText=([^&]+)', 1),
          get_json_object('{"name":"莫南","age":18}', '$.name'),
          get_json_object('{"name":"莫南","age":18}', '$.age'),
          get_json_int('{"name":"莫南","age":18}', '$.age'),
          from_json('{"name":"莫南","age":18}', 'name string, age int'),
          visit_time,
          substr(visit_time, 1, 10),
          timestamp(visit_time) `timestamp(visit_time)`,
          date_trunc('minute', visit_time),
          date_trunc('hour', visit_time),
          date_floor(visit_time, '5 second'),
          date_floor(visit_time, '1 minute'),
          date_floor(visit_time, '1 hour'),
          now(),
          from_unixtime(1000L),
          from_unixtime_millis(1000L),
          to_unix_timestamp(now()),
          to_unix_timestamp('1970-01-01 00:00:10'),
          to_unix_timestamp(timestamp('1970-01-01 00:00:10')),
          unix_timestamp() `unix_timestamp()`,
          unix_timestamp('1970-01-01 00:00:10') `unix_timestamp('1970-01-01 00:00:10')`,
          1 << 20,
          pow(2, 20),
          round(3.1415, 3),
          round(3.1415),
          floor(3.1415),
          ceil(3.1415),
          to_base64(aes_encrypt('abc', 'fd6b639dbcff0c2a', '77b07a672d57d64c')),
          string(aes_decrypt(from_base64('y+49jBd/xd6Kz4pfoQIBbA=='), 'fd6b639dbcff0c2a', '77b07a672d57d64c')),
          hex(aes_encrypt('abc', 'fd6b639dbcff0c2a', '77b07a672d57d64c')),
          string(aes_decrypt(unhex('cbee3d8c177fc5de8acf8a5fa102016c'), 'fd6b639dbcff0c2a', '77b07a672d57d64c')),
          8 << 2,
          8 >> 2,
          8 >>> 2,
          -1 << 2,
          -1 >> 2,
          -1 >>> 2,
          bin(-1, true),
          bin(-2, true),
          bin(1073741823, true),
          1 & 2,
          1 | 2,
          1 ^ 2,
          ~1,
          0 nop
      from tbl

sinks:
  - type: print
    name: print_sink
    inputs: [ query ]
    print_mode: stdout
    encoding:
      codec: json
      pretty: true
      write_null: true

active_sinks: [print_sink]